theme: jekyll-theme-minimal
title: R Contribution Site
logo: /assets/img/Rlogo.svg
description:
show_downloads: false
owner_name: the R Contribution Working Group
navigation:
  - title: Home
    url: /
  - title: Slack Group
    url: slack
  - title: Events
    url: events
  - title: Tutorials
    url: tutorials
  - title: Guide to R Development
    url: https://forwards.github.io/rdevguide/
  - title: R Contribution Working Group
    url: working-group
  - title: R Developer Page
    url: https://developer.r-project.org/
