# Hourly scraping
name: nifty50scraped

# Controls when the action will run.
on:
  push:
    branches: main


jobs: 
  autoscrape:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Load repo and install R
    steps:
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
    - uses: actions/checkout@v3
    - uses: actions/checkout@v3
      with: 
        repository: shrish-shete20/r-svn
        path: r-svn
    - uses: r-lib/actions/setup-r@v2
    - name: Install packages
      run: |
        R -e 'install.packages("ISOcodes")'
        R -e 'install.packages("dplyr")'
        R -e 'install.packages("purrr")'
        R -e 'install.packages("readr")'
        R -e 'install.packages("tidyr")'
        R -e 'install.packages("utf8")'
        R -e 'install.packages("withr")'
        R -e 'install.packages("stringr")'
    # Run R script
    - name: Scrape
      run: Rscript collaboration_campfires/translations/translation_status.R
